"""init

Revision ID: a8c10372e1a9
Revises: 
Create Date: 2025-08-18 07:15:51.331088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c10372e1a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_captures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_site', sa.String(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('apply_url_hint', sa.Text(), nullable=True),
    sa.Column('seniority_hint', sa.String(), nullable=True),
    sa.Column('compensation_hint', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('hard_errors', sa.JSON(), nullable=True),
    sa.Column('soft_warnings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('source_host', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('new', 'alive', 'dead_link', 'login_wall', 'expired', 'needs_review', 'resolved_ats', 'no_ats_link', 'error', name='posting_status'), nullable=False),
    sa.Column('next_action', sa.Enum('tailor_resume', 'review_details', 'retry_fetch', 'drop', 'none', name='posting_next_action'), nullable=False),
    sa.Column('capture_ids', sa.JSON(), nullable=True),
    sa.Column('dedupe_key_exact', sa.String(), nullable=False),
    sa.Column('dedupe_key_company_title_host', sa.String(), nullable=False),
    sa.Column('ats_req_id', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url', name='uq_job_postings_canonical_url')
    )
    op.create_index('ix_job_postings_company', 'job_postings', ['company'], unique=False)
    op.create_index('ix_job_postings_dk_cth', 'job_postings', ['dedupe_key_company_title_host'], unique=False)
    op.create_index('ix_job_postings_dk_exact', 'job_postings', ['dedupe_key_exact'], unique=False)
    op.create_index('ix_job_postings_status', 'job_postings', ['status'], unique=False)
    op.create_table('ats_resolutions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('posting_id', sa.String(), nullable=False),
    sa.Column('ats_type', sa.Enum('workday', 'greenhouse', 'lever', 'smartrecruiters', 'icims', 'taleo', 'ashby', 'bamboohr', 'teamtailor', 'unknown', name='ats_type'), nullable=False),
    sa.Column('ats_url', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ats_resolutions')
    op.drop_index('ix_job_postings_status', table_name='job_postings')
    op.drop_index('ix_job_postings_dk_exact', table_name='job_postings')
    op.drop_index('ix_job_postings_dk_cth', table_name='job_postings')
    op.drop_index('ix_job_postings_company', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_table('job_captures')
    # ### end Alembic commands ###
